import React from 'react';
import manifest from '../../data/responsiveImages.json';

type Entry = { base: string; widths: number[]; w: number; h: number };
const IMAGES = manifest as Record<string, Entry>;

/**
 * An /images/... photo served as responsive AVIF/WebP from /images/sized
 * (generated by scripts/generate-responsive-images.cjs); the original stays
 * the <img> fallback. Images not listed in the script render as a plain <img>.
 * `sizes` must describe the width the image is actually painted at — for
 * `object-cover` in a box with a different aspect ratio, that can be wider
 * than the box.
 */
export function ResponsivePicture({
  src,
  alt,
  sizes,
  className,
  style,
  loading = 'lazy',
  fetchPriority,
  'aria-hidden': ariaHidden,
}: {
  src: string;
  alt: string;
  sizes: string;
  className?: string;
  style?: React.CSSProperties;
  loading?: 'lazy' | 'eager';
  fetchPriority?: 'high' | 'low' | 'auto';
  'aria-hidden'?: boolean;
}) {
  const entry = IMAGES[src];
  const img = (
    <img
      src={src}
      alt={alt}
      width={entry?.w}
      height={entry?.h}
      className={className}
      style={style}
      loading={loading}
      decoding="async"
      fetchPriority={fetchPriority}
      aria-hidden={ariaHidden}
    />
  );
  if (!entry) return img;

  const srcSet = (ext: string) => entry.widths.map((w) => `${entry.base}-${w}.${ext} ${w}w`).join(', ');
  return (
    <picture>
      <source type="image/avif" sizes={sizes} srcSet={srcSet('avif')} />
      <source type="image/webp" sizes={sizes} srcSet={srcSet('webp')} />
      {img}
    </picture>
  );
}
