/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}', './public/index.html'],
  theme: {
    extend: {
      colors: {
        'surface-container-low': '#f0f3ff',
        'surface-tint': '#b91c1c',
        secondary: '#735c00',
        tertiary: '#3c475b',
        'inverse-on-surface': '#ecf1ff',
        surface: '#f9f9ff',
        'on-background': '#111c2d',
        background: '#f9f9ff',
        'on-surface-variant': '#5b403d',
        'surface-container-lowest': '#ffffff',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'surface-dim': '#cfdaf2',
        primary: '#93000b',
        outline: '#8f6f6c',
        'secondary-container': '#fed01b',
        'on-primary': '#ffffff',
        'outline-variant': '#e4beb9',
        'surface-container': '#e7eeff',
        'surface-container-highest': '#d8e3fb',
        'tertiary-container': '#545f73',
        'primary-container': '#b91c1c',
        'surface-container-high': '#dee8ff',
        'on-surface': '#111c2d',
        'on-secondary': '#ffffff',
        'on-tertiary': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'on-secondary-container': '#6f5900',
      },
      fontFamily: {
        headline: ['"Noto Serif"', 'Georgia', 'serif'],
        body: ['"Noto Serif"', 'Georgia', 'serif'],
        label: ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [],
};
